CREATE TABLE `mensagem` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`ASSUNTO` VARCHAR(120) NOT NULL COLLATE 'utf8_general_ci',
	`DATA_CRIACAO` DATETIME NOT NULL,
	`MENSAGEM` VARCHAR(10000) NOT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`ID`) USING BTREE
) COLLATE='utf8_general_ci' ENGINE=InnoDB;

CREATE TABLE `notificacao` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`DATA_LEITURA` DATETIME NOT NULL,
	`DESTINATARIO` BIGINT(20) NOT NULL,
	`MENSAGEM` BIGINT(20) NOT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `FK8o7bxii6o0ehdgggy4jffa0lg` (`DESTINATARIO`) USING BTREE,
	INDEX `FKtlcme0l2fmxd7uwtxy4no592c` (`MENSAGEM`) USING BTREE,
	CONSTRAINT `FK8o7bxii6o0ehdgggy4jffa0lg` FOREIGN KEY (`DESTINATARIO`) REFERENCES `comunicacicom`.`usuario` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `FKtlcme0l2fmxd7uwtxy4no592c` FOREIGN KEY (`MENSAGEM`) REFERENCES `comunicacicom`.`mensagem` (`ID`) ON UPDATE RESTRICT ON DELETE RESTRICT
) COLLATE='utf8_general_ci' ENGINE=InnoDB;